name: historias_encantadas
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter_localizations:
    sdk: flutter
  intl: any

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  audioplayers: ^6.5.1
  flutter_tts: ^4.0.2
  http: ^1.2.1
  path_provider: ^2.1.1
  sqflite: ^2.4.2
  path: ^1.9.1
  provider: ^6.1.5+1
  country_icons: ^3.0.0
  flutter_svg: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:


  generate: true
  uses-material-design: true

  assets:
    - assets/images/back.png
    - assets/images/background.png
    - assets/images/snowWhite/
    - assets/images/redHat/
    - assets/images/icons/
    - assets/images/threeLittlePigs/
    - assets/sounds/pt/redHat/
    - assets/sounds/pt/snowWhite/
    - assets/sounds/pt/threeLittlePigs/
    - assets/flags/br.svg
    - assets/flags/cn.svg
    - assets/flags/es.svg
    - assets/flags/fr.svg
    - assets/flags/us.svg

l10n:
  arb-dir: lib/l10n
  output-dir: lib/generated
  template-arb-file: app_pt.arb
  output-localization-file: l10n.dart
  output-class: S

